version: "3.4"
services:
  nexus:
    image: sonatype/nexus3
    network_mode: bridge
    volumes:
      - nexus-data:/nexus-data
      - nexus-blobs:/nexus-data/blobs
      - /etc/docker/nexus.vmoptions:/opt/sonatype/nexus/bin/nexus.vmoptions
    ports:
      - 8081:8081
      - 12345:12345
volumes:
  nexus-data: {}
  nexus-blobs: {}
